# Site settings
title: Sabina's Game Journey
description: Sabina's Game-Creating Journey (Neither the "Home" nor "About" buttons work don't try them lol)
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/game/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://techiesabina.github.io/game/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: techiesabina #github username
repo: gmae #github repository
branch: master #branch
relative_source: ../game/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://techiesabina.github.io/game/
source_url:  https://github.com/techiesabina/game #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
